/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as SurveyTokenRouteImport } from './routes/survey.$token'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout/analytics'
import { Route as LayoutAlertsRouteImport } from './routes/_layout/alerts'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as ConsentTokenDeclineRouteImport } from './routes/consent/$token/decline'
import { Route as ConsentTokenAcceptRouteImport } from './routes/consent/$token/accept'
import { Route as LayoutStudentsStudentIdRouteImport } from './routes/_layout/students.$studentId'
import { Route as LayoutAdminStudentsRouteImport } from './routes/_layout/admin.students'
import { Route as LayoutAdminQuestionsRouteImport } from './routes/_layout/admin.questions'
import { Route as LayoutAdminGroupsRouteImport } from './routes/_layout/admin.groups'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const SurveyTokenRoute = SurveyTokenRouteImport.update({
  id: '/survey/$token',
  path: '/survey/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlertsRoute = LayoutAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const ConsentTokenDeclineRoute = ConsentTokenDeclineRouteImport.update({
  id: '/consent/$token/decline',
  path: '/consent/$token/decline',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentTokenAcceptRoute = ConsentTokenAcceptRouteImport.update({
  id: '/consent/$token/accept',
  path: '/consent/$token/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutStudentsStudentIdRoute = LayoutStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminStudentsRoute = LayoutAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminQuestionsRoute = LayoutAdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminGroupsRoute = LayoutAdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/alerts': typeof LayoutAlertsRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/': typeof LayoutIndexRoute
  '/admin/groups': typeof LayoutAdminGroupsRoute
  '/admin/questions': typeof LayoutAdminQuestionsRoute
  '/admin/students': typeof LayoutAdminStudentsRoute
  '/students/$studentId': typeof LayoutStudentsStudentIdRoute
  '/consent/$token/accept': typeof ConsentTokenAcceptRoute
  '/consent/$token/decline': typeof ConsentTokenDeclineRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/alerts': typeof LayoutAlertsRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/': typeof LayoutIndexRoute
  '/admin/groups': typeof LayoutAdminGroupsRoute
  '/admin/questions': typeof LayoutAdminQuestionsRoute
  '/admin/students': typeof LayoutAdminStudentsRoute
  '/students/$studentId': typeof LayoutStudentsStudentIdRoute
  '/consent/$token/accept': typeof ConsentTokenAcceptRoute
  '/consent/$token/decline': typeof ConsentTokenDeclineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/alerts': typeof LayoutAlertsRoute
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/groups': typeof LayoutAdminGroupsRoute
  '/_layout/admin/questions': typeof LayoutAdminQuestionsRoute
  '/_layout/admin/students': typeof LayoutAdminStudentsRoute
  '/_layout/students/$studentId': typeof LayoutStudentsStudentIdRoute
  '/consent/$token/accept': typeof ConsentTokenAcceptRoute
  '/consent/$token/decline': typeof ConsentTokenDeclineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/items'
    | '/settings'
    | '/survey/$token'
    | '/'
    | '/admin/groups'
    | '/admin/questions'
    | '/admin/students'
    | '/students/$studentId'
    | '/consent/$token/accept'
    | '/consent/$token/decline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/items'
    | '/settings'
    | '/survey/$token'
    | '/'
    | '/admin/groups'
    | '/admin/questions'
    | '/admin/students'
    | '/students/$studentId'
    | '/consent/$token/accept'
    | '/consent/$token/decline'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/alerts'
    | '/_layout/analytics'
    | '/_layout/items'
    | '/_layout/settings'
    | '/survey/$token'
    | '/_layout/'
    | '/_layout/admin/groups'
    | '/_layout/admin/questions'
    | '/_layout/admin/students'
    | '/_layout/students/$studentId'
    | '/consent/$token/accept'
    | '/consent/$token/decline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SurveyTokenRoute: typeof SurveyTokenRoute
  ConsentTokenAcceptRoute: typeof ConsentTokenAcceptRoute
  ConsentTokenDeclineRoute: typeof ConsentTokenDeclineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/survey/$token': {
      id: '/survey/$token'
      path: '/survey/$token'
      fullPath: '/survey/$token'
      preLoaderRoute: typeof SurveyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/alerts': {
      id: '/_layout/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof LayoutAlertsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/consent/$token/decline': {
      id: '/consent/$token/decline'
      path: '/consent/$token/decline'
      fullPath: '/consent/$token/decline'
      preLoaderRoute: typeof ConsentTokenDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent/$token/accept': {
      id: '/consent/$token/accept'
      path: '/consent/$token/accept'
      fullPath: '/consent/$token/accept'
      preLoaderRoute: typeof ConsentTokenAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/students/$studentId': {
      id: '/_layout/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof LayoutStudentsStudentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/students': {
      id: '/_layout/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof LayoutAdminStudentsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/questions': {
      id: '/_layout/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof LayoutAdminQuestionsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/groups': {
      id: '/_layout/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof LayoutAdminGroupsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminGroupsRoute: typeof LayoutAdminGroupsRoute
  LayoutAdminQuestionsRoute: typeof LayoutAdminQuestionsRoute
  LayoutAdminStudentsRoute: typeof LayoutAdminStudentsRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminGroupsRoute: LayoutAdminGroupsRoute,
  LayoutAdminQuestionsRoute: LayoutAdminQuestionsRoute,
  LayoutAdminStudentsRoute: LayoutAdminStudentsRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutAlertsRoute: typeof LayoutAlertsRoute
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutStudentsStudentIdRoute: typeof LayoutStudentsStudentIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutAlertsRoute: LayoutAlertsRoute,
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutStudentsStudentIdRoute: LayoutStudentsStudentIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SurveyTokenRoute: SurveyTokenRoute,
  ConsentTokenAcceptRoute: ConsentTokenAcceptRoute,
  ConsentTokenDeclineRoute: ConsentTokenDeclineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
